//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTFEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTFEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap backgroundpattern {
            get {
                object obj = ResourceManager.GetObject("backgroundpattern", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1{\b\ul KEYS}\par
        ///\par
        ///1            Bottom view\par
        ///2            Top view\par
        ///3            Back view\par
        ///4            Front view\par
        ///5            Right view\par
        ///6            Left view\par
        ///\par
        ///A            Increase brightness\par
        ///Z            Decrease brightness\par
        ///Shift+A      Full brightness\par
        ///Shift+Z      Zero brightness\par
        ///\par
        ///B            Toggle background between white &amp; black\par
        ///W            Toggle model between solid &amp; wireframe\par
        ///\par
        ///*            Increase size of hard [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelViewHelp {
            get {
                return ResourceManager.GetString("ModelViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancer UTF Editor
        ///
        ///This is a version of the Freelancer UTF editor. It continues the work of Colin Sanby and Mario &apos;HCl&apos; Brito.
        ///
        ///You should be able to find the latest version of this software at http://the-starport.net.
        ///
        ///This program is free software. You may do what you like with it but don&apos;t forget to the credit the people who made this possible.
        ///
        ///==== Changes in 2.1 ====
        ///
        ///* Reads the model materials from the parent and grandparent directories; expands the root node automatically; and shows t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
    }
}
